version: '3'

services:

  todos_service:
    build: ./todos_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./todos_service/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:15.4-alpine
    env_file: .env
    restart: always
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres: